name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Debug: show repo structure
      - name: Debug Repo Structure
        run: |
          echo "Repo root:"
          ls -R

      # Setup Node.js for React build
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Build React frontend
      - name: Build React App
        run: |
          cd client
          npm install
          CI=false npm run build
          echo "Build output:"
          ls -R build || echo "⚠️ Build folder not found"

      # Deploy React + .NET backend
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          #### Locations
          app_location: "client"          # React app (where package.json lives)
          api_location: "server"          # .NET backend
          output_location: "build"        # React build folder inside client/
