name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      # Build React frontend
      - name: Build React App
        run: |
          cd client
          npm install
          npm run build

      # Deploy React + .NET API
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          #### Locations
          app_location: "client"          # React app folder
          api_location: "server"          # .NET backend
          output_location: "build"    
          name: List build folder
          run: |
           ls -R client/build
# React build folder inside /client

