name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Show repo structure for debugging
      - name: Debug Repo Structure
        run: |
          echo "Repo root:"
          ls -R

      # Setup Node.js 20 for React build
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Build React frontend
      - name: Build React App
        run: |
          cd client
          npm install
          npm run build
          echo "React build output:"
          ls -R build

      # Deploy React + .NET API
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "client"        # React app folder
          api_location: "server"        # .NET backend folder
          output_location: "build"      # React build output
